version: "3.9"
services:
  db:
    image: postgres:13
    restart: always
  redis:
    image: redis:6
  worker:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .://usr/src/app
      - /usr/src/app/tmp
    command: bundle exec sidekiq
    env_file:
      - .env
    depends_on:
      - redis
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .://usr/src/app
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - db
      - worker

